language: php
services: docker

php:
  - 5.6
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  # PHP syntax check
  - bash -c '! (find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l | grep "Parse error")'
  # PHP cs fixer
  - vendor/bin/php-cs-fixer fix --no-interaction --dry-run --diff --using-cache=no --diff-format udiff
  # PHP Stan
  - if [ ${TRAVIS_PHP_VERSION:0:2} == "7." ]; then
      docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7;
      docker exec -ti temp-ps rm -rf /var/www/html/modules/ps_themecusto;
      docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/ps_themecusto -e _PS_ROOT_DIR_=/var/www/html --workdir=/var/www/html/modules/ps_themecusto quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/ps_themecusto/tests/phpstan/phpstan.neon;
    fi
